version: '3.8'
services:
  server:
    build: .
    command: python main.py server
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  client:
    build: .
    command: python main.py client
    depends_on:
      - server
