services:
  server:
    build: .
    command: python3 main.py server
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  # client:
  #   build: .
  #   command: python main.py client
  #   depends_on:
  #     - server
  streamlit:
    build: .
    command: python3 main.py streamlit --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - server
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
